
package net.bncloud.bis.srm.doc.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SRMDocInfoServicePortType", targetNamespace = "http://service.it.meishang.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SRMDocInfoServicePortType {


    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns net.bncloud.bis.srm.doc.webservice.ArrayOfAnyType2AnyTypeMap
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.it.meishang.com")
    @RequestWrapper(localName = "getDocInfoList", targetNamespace = "http://service.it.meishang.com", className = "net.bncloud.bis.srm.doc.webservice.GetDocInfoList")
    @ResponseWrapper(localName = "getDocInfoListResponse", targetNamespace = "http://service.it.meishang.com", className = "net.bncloud.bis.srm.doc.webservice.GetDocInfoListResponse")
    public ArrayOfAnyType2AnyTypeMap getDocInfoList(
        @WebParam(name = "in0", targetNamespace = "http://service.it.meishang.com")
        Integer in0,
        @WebParam(name = "in1", targetNamespace = "http://service.it.meishang.com")
        ArrayOfInt in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns net.bncloud.bis.srm.doc.webservice.ArrayOfAnyType2AnyTypeMap
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://service.it.meishang.com")
    @RequestWrapper(localName = "getDocFileList", targetNamespace = "http://service.it.meishang.com", className = "net.bncloud.bis.srm.doc.webservice.GetDocFileList")
    @ResponseWrapper(localName = "getDocFileListResponse", targetNamespace = "http://service.it.meishang.com", className = "net.bncloud.bis.srm.doc.webservice.GetDocFileListResponse")
    public ArrayOfAnyType2AnyTypeMap getDocFileList(
        @WebParam(name = "in0", targetNamespace = "http://service.it.meishang.com")
        Integer in0,
        @WebParam(name = "in1", targetNamespace = "http://service.it.meishang.com")
        ArrayOfInt in1);

}
